"""FastAPI ranking service.

The response is a ranked list with reasons and an availability tier, not a
single office id. Three things are always included:

* the **ranking**, because access and catering can be prepared for two
  buildings when the model is unsure and that is cheaper than being wrong;
* the **availability tier**, because a prediction for a first-time visitor
  rests on far less than one for a regular, and the consumer should be able to
  see which it got;
* the **top contributing features**, because "go to building 3" is an
  instruction nobody audits and "go to building 3, you went there last time
  and your team sits there" is one somebody can correct.
"""

from __future__ import annotations

from datetime import date
from functools import lru_cache

import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from ..config import OUT_DIR
from ..models import availability, explain

app = FastAPI(
    title="office-visit-ranker",
    version="0.1.0",
    description="Ranks the offices a travelling employee is likely to visit. Synthetic data.",
)


class RankRequest(BaseModel):
    emp_id: str = Field(..., examples=["E500123"])
    destination_city: str = Field(..., examples=["Ashvale"])
    arrival_date: date | None = None
    slots: int = Field(3, ge=1, le=12)


class RankedOffice(BaseModel):
    rank: int
    office_id: str
    score: float
    reasons: list[str]


class RankResponse(BaseModel):
    emp_id: str
    destination_city: str
    availability_mask: str
    scored_by_model: str
    fallback_steps: int
    top1_probability: float | None
    abstained: bool
    ranking: list[RankedOffice]


@lru_cache(maxsize=1)
def _artifacts():
    path = OUT_DIR / "candidates.parquet"
    if not path.exists():
        raise FileNotFoundError("No feature frame. Run `make pipeline` before serving.")
    frame = pd.read_parquet(path)

    from ..features.build import build_candidates  # noqa: F401  (documented below)
    from ..models import ranker

    # The service scores from the most recent candidate rows rather than
    # rebuilding features per request. Rebuilding would need the full visit
    # history in the request path; a production version would read those
    # features from a store, which is the same shape with a different backend.
    train = frame[frame["split"] == "train"]
    validation = frame[frame["split"] == "validation"]
    family = ranker.train_family(train, validation)
    return frame, family


@app.get("/health")
def health() -> dict:
    try:
        frame, family = _artifacts()
    except FileNotFoundError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    return {
        "status": "ok",
        "models": sorted(family.models),
        "trips_available": int(frame["trip_id"].nunique()),
    }


@app.get("/model-info")
def model_info() -> dict:
    frame, family = _artifacts()
    return {
        "models": {
            key: {"n_features": len(columns), "features": columns}
            for key, columns in family.features.items()
        },
        "fallback_order": list(availability.FALLBACK_ORDER),
        "min_training_trips_per_mask": availability.MIN_TRAINING_TRIPS,
        "data": "synthetic; generated by this repository",
        "caveat": (
            "Accuracy differs sharply by availability tier and by how many offices the "
            "destination city has. A first-visit prediction is materially weaker than a "
            "repeat-visit one, and the response says which it is."
        ),
    }


@app.post("/rank", response_model=RankResponse)
def rank(request: RankRequest) -> RankResponse:
    frame, family = _artifacts()

    rows = frame[
        (frame["emp_id"] == request.emp_id)
        & (frame["destination_city"] == request.destination_city)
    ]
    if rows.empty:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No candidate rows for {request.emp_id} in {request.destination_city}. "
                "The employee may not exist, or the city may have no offices."
            ),
        )
    # Most recent trip's candidate rows for this pair.
    latest = rows["arrival_date"].max()
    rows = rows[rows["arrival_date"] == latest].copy()

    scored = family.score(rows)
    scored = scored.sort_values("score", ascending=False)

    model_key = str(scored["scored_by"].iloc[0])
    columns = family.features[model_key]
    explanation = explain.explain_trip(
        family.models[model_key], scored, columns, top_k=3
    ).set_index("office_id")

    top = scored.iloc[0]
    margin = float(top["score"] - scored["score"].iloc[1]) if len(scored) > 1 else 10.0
    # A plain logistic squash of the margin. The isotonic calibrator fitted in
    # the pipeline is the right thing to load here; this keeps the service
    # self-contained and is labelled as an approximation rather than presented
    # as a calibrated probability.
    probability = float(1.0 / (1.0 + np.exp(-margin)))

    ranking = []
    for position, row in enumerate(scored.head(request.slots).itertuples(index=False), start=1):
        drivers = explanation.loc[row.office_id, "top_drivers"] if len(explanation) else ""
        ranking.append(
            RankedOffice(
                rank=position,
                office_id=str(row.office_id),
                score=round(float(row.score), 4),
                reasons=[d.strip() for d in str(drivers).split(";") if d.strip()],
            )
        )

    return RankResponse(
        emp_id=request.emp_id,
        destination_city=request.destination_city,
        availability_mask=str(scored["mask_key"].iloc[0]),
        scored_by_model=model_key,
        fallback_steps=int(scored["fallback_steps"].iloc[0]),
        top1_probability=round(probability, 4),
        abstained=bool(probability < 0.70),
        ranking=ranking,
    )
